name: testing
on: push
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: install dependencies
      run: npm ci 
    - name: lint
      run: npm run lint
    - name: testing
      run: npm run test
    - name: building
      run: npm run build                     